### ISSUE TITLE
socket.io 404 not-found

### ISSUE THREAD

**Issue by yura-master-web** [kvasdopil/react-lect1#1]
Здравствуйте, я как то месяца 4 назад смотрел вашу презентацию и скопировал ваше приложение и запустил у себя на машине. Тогда сервер выдавал ошибку socket.io 404 not-found . Но я вроде бы установил npm i socket.io или socket (просто ) -g  и ошибка ушла , приложение заработало. Так вот я windows переустановил и решил еще раз по разбираться в этом коде. Только вот сейчас не как не могу избавиться от этой ошибки. Подскажите что за пакет socket нужно установить глобально. ( да вроде помнется что глобально ставил )

**Comment by kvasdopil** [comment]
Привет, судя по всему достаточно просто сделать `npm install socket.io` и всё установится. А чо пишет?

**Comment by yura-master-web** [comment]
[Fri Aug 25 2017 13:40:53 GMT+0300 (RTZ 2 (зима))] "GET /socket.io/?EIO=2&transport=polling&t=1503657653473-0" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 YaBrowser/17.7.1.726 Yowser/2.5 Safari/537.36"

[Fri Aug 25 2017 13:40:53 GMT+0300 (RTZ 2 (зима))] "GET /socket.io/?EIO=2&transport=polling&t=1503657653473-0" Error (404): "Not found"

[Fri Aug 25 2017 13:40:54 GMT+0300 (RTZ 2 (зима))] "GET /socket.io/?EIO=2&transport=polling&t=1503657654511-1" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 YaBrowser/17.7.1.726 Yowser/2.5 Safari/537.36"
Это то что выдает http-server -p 8088  (после запуска и захода на страницу в браузере)
Нижняя строка - то что видно в консоле браузера
GET http://localhost:8088/socket.io/?EIO=2&transport=polling&t=1503657748727-15 404 (Not Found)

Я уже поставил и socket.io и просто socket

**Comment by kvasdopil** [comment]
Сервер нужно запускать командой `node server/index.js`

**Comment by yura-master-web** [comment]
Спасибо. )
